Fix bugs
tropycal/tropycal pull request #135
Opened 2021-09-26 19:31 UTC by tomerburg

Several bug fixes:

- Some post-tropical cyclones have had their storm type incorrectly assigned as a tropical cyclone in ``RealtimeStorm.get_realtime_info()``. This has been changed to "Post-Tropical Cyclone".
- Storm plotting functions are split between dashed lines for non-tropical cyclones and solid lines for tropical cyclones. The immediate timestep before a TC forms was plotted with a solid black line, but has been changed to a thin black line.
- When adding invest handling capability for Tropycal v0.3, a case that wasn't considered is a tropical cyclone which became post-tropical, then re-assigned as an invest to monitor the potential for re-transitioning into a tropical cyclone. The resulting unintended behavior was for Realtime objects to re-assign those as active tropical cyclones, even though no operational products are produced for such cases. This bug fix reassigns any post-tropical cyclone that has not been tropical for 18+ hours as an invest.
- When reading in JTWC data into a Realtime object, the "TY" typhoon storm type is reassigned to "HU" (hurricane) for continuity purposes between different basins. For some data sources, a Super Typhoon "ST" storm type is included, which was previously not accounted for, resulting in an incorrect classification as an extratropical cyclone. This bug fixes ensures super typhoons are also reassigned to a "HU" storm type.

2021-09-26 19:32 UTC, tomerburg commented
As some of these bug fixes are critical (e.g., super typhoon & invest handling), once this PR is merged, it will be released on pip & conda as Tropycal v0.3.1.

2021-09-27 00:48 UTC, TomerAberbach requested changes
I think there are a few issues with the current fixes:
- We're duplicating the same arrays in a few places. Duplication is sometimes warranted, but in this case I think it just makes it more likely that the arrays become out of sync.
- Specifying the arrays in the function itself means a new array of that size is allocated for each usage for each function call, which is a bit wasteful
- `x in [1, 2, 3, ..., n]` checks take linear time in the worst case

I think instead we should define `frozenset` constants and reference those instead. Example:
```python
# Top-level
NON_TROPICAL_STORM_TYPES = frozenset(['SD','SS','TD','TS','HU'])

def some_func():
    # ...

    if type in NON_TROPICAL_STORM_TYPES:
        # ...
```

The advantages are:
- No duplication of the values
- No multiple allocations of the same array
- Because we are using a set, which is optimized for querying, `x in SOME_SET` takes constant time on average

Note the example uses a `frozenset` because we don't expect the set values to change ("frozen" makes it so that you cannot modify it after initialization)

2021-09-29 23:22 UTC, tomerburg commented
Following the previous suggestion a new constants.py file has been added, with these constants for tropical cyclone types referenced where applicable throughout the package.

Additional minor bug fixes were also caught and fixed in the meantime:

- When plotting a RealtimeStorm object, the displayed name treated invests and post-tropical cyclones equally. This has now been fixed such that invests will have their names displayed following invest naming conventions (e.g., "Invest 91L"), while post-tropical cyclones that have been re-designated as invests retain their original name (e.g., "Tropical Storm Peter").
- Central Pacific storms can now have their previous operational forecast data (from the a-deck) accessed.
- Realtime objects now delete invests after 9 hours of inactivity, vs. 18 hours for tropical cyclones. In the future this can be optimized further to automatically delete invests that were re-classified as tropical cyclones.

2021-09-30 03:04 UTC, TomerAberbach requested changes

2021-09-30 03:04 UTC, TomerAberbach commented on src/tropycal/realtime/storm.py
> +                if 'SD' not in self.type and 'SS' not in self.type and 'TD' not in self.type and 'TS' not in self.type and 'HU' not in self.type:
Can write this instead I think:
```python
if all(type not in self.type for type in constants.TROPICAL_STORM_TYPES):
```

2021-09-30 03:04 UTC, TomerAberbach commented on src/tropycal/tracks/dataset.py
> +                        if hhmm in ['0000','0600','1200','1800'] and neumann_type in constants.NAMED_TROPICAL_STORM_TYPES:
Should `['0000','0600','1200','1800']` be a `frozenset` in `constants.py` since it's used in multiple places?

2021-10-01 03:10 UTC, TomerAberbach commented on src/tropycal/realtime/realtime.py
> +                if hours_diff >= 18.0: del self.data[key]
Or even:
```python
if hours_diff >= (9.0 if self.data[key]['invest'] else 18.0):
  del self.data[key]
```

But that may be a little less readable than my other suggestion

2021-10-04 20:02 UTC, tomerburg commented on src/tropycal/realtime/realtime.py
> +                    if btk_type == "TY" or btk_type == "ST": btk_type = "HU"
These types represent Typhoon and Super-Typhoon, respectively - the latter is a subset of typhoons (i.e., typhoons above a certain intensity). The only two places where the TY and ST types are relevant in the code is here and in tracks.TrackDataset where all storm types across all basins are conformed to the same naming convention used in the Atlantic and East Pacific oceans (i.e., SD, SS, TD, TS, HU), as this simplifies calculations. In the meantime I don't think this needs a frozenset, but if this changes in the future this may need to be moved to a frozenset.

2021-10-04 23:22 UTC, tomerburg commented on src/tropycal/realtime/realtime.py
> +                pass
The variable ``last_tropical_date`` isn't always defined - it's only defined if a storm was ever a tropical cyclone. In hindsight this is not the best coding practice, and I replaced the try-except block with an if statement.

2021-10-04 23:25 UTC, tomerburg commented
The following suggestions to clean up the code were applied, along with a few other bug fixes that were caught in the meantime:

- The function ``tracks.Storm.sel()`` only accepted hard int or float types, and crashed if any other variation of int or float types (e.g, numpy) were input. This bug fix ensures any type of integer or float, including all numpy variations, can be accepted as arguments.
- Several functions from ``tracks.TrackDataset`` were discovered to have been inadvertedly removed in a PR last year. These functions were re-added and slightly cleaned up.

2021-10-04 23:40 UTC, TomerAberbach approved these changes

2021-10-04 23:40 UTC, TomerAberbach commented on src/tropycal/realtime/realtime.py
> +            if True in [type in self.data[stormid]['type'] for type in constants.TROPICAL_STORM_TYPES]:
I think what you're looking for here is `if any(type in self.data[stormid]['type'] for type in constants.TROPICAL_STORM_TYPES)`? (which corresponds to "at least one True")

2021-10-04 23:40 UTC, TomerAberbach commented on src/tropycal/tracks/dataset.py
> +    def to_dataframe(self):
This is kind of an overall comment: I think you have a decent number of comments in here that are unnecessary. For example, in this code:
```python
#Get season summary
season_summary = self.get_season(season).summary()
```
The comment feels redundant because the code literally says "season summary = get season ... summary". Maybe go through the comments and remove some of them if you think they aren't aiding in readability?

2021-10-04 23:40 UTC, TomerAberbach commented on src/tropycal/tracks/dataset.py
> +        if isinstance(year_range,(list,tuple)) == False:
Replace `== False` with `not` before the condition (same for below)

2021-10-04 23:45 UTC, merged

2021-10-05 00:02 UTC, tomerburg commented
Closing this PR before adding the remaining suggestions was a mistake on my end... these will be addressed in a separate PR I am currently working on.

2021-10-05 00:14 UTC, tomerburg commented on src/tropycal/tracks/dataset.py
> +    def to_dataframe(self):
I removed the comments that are most obviously redundant for my new PR - will save the full comment clean-up for a separate PR.

2021-10-05 00:14 UTC, tomerburg commented on src/tropycal/realtime/realtime.py
> +            if True in [type in self.data[stormid]['type'] for type in constants.TROPICAL_STORM_TYPES]:
Yes, that's an even cleaner way of writing it!